int _putchar(char c);
void print_alphabet(void);
int _islower(int c);
void print_alphabet_x10(void);
int _isalpha(int c);
int print_sign(int n);
int _abs(int);
int add(int, int);
int print_last_digit(int);
void print_to_98(int n);
